Repository OpenVoiceOS/ovos-dinkum-listener, pull requests merged in 2023-09, with the labels that each got.

#59 Fix README.MD and Added Timeout_Seconds_With_Silence
  README.md
  ovos_dinkum_listener/service.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: enhancement

#60 refactor/play_sound_in_ovos_audio
  ovos_dinkum_listener/service.py
Labels: refactor

#61 fix/bind_bus
  ovos_dinkum_listener/transformers.py
Labels: bug

#62 feat extract speech
  README.md
  ovos_dinkum_listener/service.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
  requirements/requirements.txt
Labels: enhancement

#64 fix config hash not set
  ovos_dinkum_listener/service.py
Labels: bug
