Repository OpenVoiceOS/ovos-dinkum-listener, pull requests merged in 2023-05, with the labels that each got.

#16 Fix issue #12
  MANIFEST.in
  ovos_dinkum_listener/res/snd/acknowledge.mp3
  ovos_dinkum_listener/res/snd/error.mp3
  ovos_dinkum_listener/res/snd/start_listening.wav
Labels: bug

#18 fix/continuous_listen + pyaudio support (optional)
  ovos_dinkum_listener/__main__.py
  ovos_dinkum_listener/service.py
  ovos_dinkum_listener/voice_loop/microphone.py
  ovos_dinkum_listener/voice_loop/pyaudio_microphone.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: bug, enhancement

#19 feat/valid langs from session manager
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: bug, enhancement

#20 feat/microphone plugins + update logging and documentation
  README.md
  ovos_dinkum_listener/__main__.py
  ovos_dinkum_listener/service.py
  ovos_dinkum_listener/voice_loop/__init__.py
  ovos_dinkum_listener/voice_loop/hotwords.py
  ovos_dinkum_listener/voice_loop/microphone.py
  ovos_dinkum_listener/voice_loop/pyaudio_microphone.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
  requirements.txt
Labels: enhancement

#24 Add Unit Tests
  .github/workflows/unit_tests.yml
  ovos_dinkum_listener/plugins.py
  ovos_dinkum_listener/service.py
  ovos_dinkum_listener/transformers.py
  ovos_dinkum_listener/voice_loop/__init__.py
  ovos_dinkum_listener/voice_loop/hotwords.py
  requirements.txt
  requirements/requirements.txt
  requirements/tests.txt
  setup.py
  test/unittests/test_hotwords.py
  test/unittests/test_plugins.py
  test/unittests/test_service.py
  test/unittests/test_transformers.py
  test/unittests/test_voice_loop.py
Labels: enhancement

#29 Fix default mic config handling to prevent overriding configured values
  ovos_dinkum_listener/service.py
Labels: bug

#31 Play global listen sound on button press/get_response
  ovos_dinkum_listener/service.py
Labels: bug

#36 Add docstrings and type annotations to DinkumVoiceLoop
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: documentation

#37 Update README.md
  README.md
Labels: documentation

#39 Acquire lock during service shutdown to prevent reload race condition
  ovos_dinkum_listener/service.py
Labels: bug

#43 Update `main` method to match ovos-listener for compatibility
  ovos_dinkum_listener/__main__.py
Labels: bug

#44 Add call to `init_service_logger` to load LOG configuration
  ovos_dinkum_listener/__main__.py
Labels: bug

#41 Debug config reloading
  ovos_dinkum_listener/service.py
  requirements/requirements.txt
  test/unittests/test_service.py
Labels: bug
