Repository OpenVoiceOS/ovos-dinkum-listener, pull requests merged in 2023-04, with the labels that each got.

#2 feature parity with ovos-listener
  .github/workflows/notify_matrix.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .github/workflows/unit_tests.yml
  README.md
  mycroft_dinkum_listener/__main__.py
  mycroft_dinkum_listener/voice_loop/voice_loop.py
  ovos_dinkum_listener/__init__.py
  ovos_dinkum_listener/__main__.py
  ovos_dinkum_listener/plugins.py
  ovos_dinkum_listener/version.py
  ovos_dinkum_listener/voice_loop/__init__.py
  ovos_dinkum_listener/voice_loop/hotwords.py
  ovos_dinkum_listener/voice_loop/microphone.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
  requirements.txt
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  scripts/remove_alpha.py
  setup.py
Labels: enhancement

#3 feat/neon_transformers
  README.md
  ovos_dinkum_listener/__main__.py
  ovos_dinkum_listener/transformers.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: enhancement

#4 fix packaging
  setup.py
Labels: bug

#7 fix/dataclass
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: bug

#8 fix/save_stt
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: bug

#9 feat/stt_compat_no_more_flac
  README.md
  ovos_dinkum_listener/plugins.py
  ovos_dinkum_listener/transformers.py
  requirements.txt
Labels: refactor

#10 feat/fallback_stt
  README.md
  ovos_dinkum_listener/__main__.py
  ovos_dinkum_listener/plugins.py
  ovos_dinkum_listener/voice_loop/voice_loop.py
Labels: enhancement
